name: Build YTD APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Mantenemos la versión 22.04 para asegurar total compatibilidad de herramientas
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17 Oficial
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias del sistema (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev

    - name: Instalar dependencias de Python y Buildozer
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.36 buildozer==1.5.0

    - name: Compilar APK con Buildozer
      run: |
        # Al controlar las versiones estables desde tu buildozer.spec,
        # la compilación se ejecutará de forma directa sin detenerse.
        buildozer android debug

    - name: Subir APK resultante como Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: YTD-APK-Debug
        # Usamos el comodín * para que encuentre el archivo sin importar la versión exacta del .spec
        path: bin/YTD-*-debug.apk
