name: Build YTD APK

on:
  workflow_dispatch: # Esto quita la compilación automática y te devuelve el botón manual "Run workflow"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17 Oficial
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalar dependencias del sistema (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev

    - name: Instalar dependencias de Python y Buildozer
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.36 buildozer

    - name: Compilar APK con Buildozer
      run: |
        # Dejamos que buildozer gestione las licencias de forma nativa a su propio ritmo
        buildozer android debug

    - name: Subir artefacto APK
      uses: actions/upload-artifact@v4
      with:
        name: YTD-APK-Debug
        path: bin/*.apk
